In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
num_list = [1,2,3,4,5,6,7,8,9,10]

In [3]:
%timeit [i ** 2 for i in num_list]

6.22 µs ± 41.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
arr = np.array(num_list)

In [5]:
%timeit arr ** 2 # takes comparatively less time that a list operation

1.5 µs ± 15.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
# num_list + 1 # trying to add 1 to every element 

In [7]:
arr + 1 # possible with numpy after converting it to an array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
type(arr) # ndarray because it generalises the n dimensional array

numpy.ndarray

In [9]:
print(arr.ndim) # prints the dimension of the array
print(arr.shape) # prints the number of elements in the array

1
(10,)


In [10]:
np.arange(2,10) 
# be careful it's arange and not arrange - single n
# prints numbers from (first index to last index -1)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(array_2d.ndim)
print(array_2d.shape)

2
(3, 3)


---

In [13]:
np.zeros((5,5)) # zero matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.diag([1,2,3]) # diagonal matrix with the given elements across the diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
np.identity(3) # identity square matrix only

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

In [17]:
array_1 = np.random.randint(10,50, (5,4))
print (array_1)

[[15 46 28 27]
 [10 20 23 21]
 [23 35 23 10]
 [39 39 18 14]
 [44 45 11 36]]


In [18]:
array_1[-1] # returns that row acc. to the index

array([44, 45, 11, 36])

In [19]:
array_1[2,1]

35

In [20]:
array_1[1:4, 2:4] # slicing
# array_name[start_row_index: end_row_index +1 , start_col_index: end_col_index + 1]

array([[23, 21],
       [23, 10],
       [18, 14]])

In [21]:
array_1[1:, 2:] # row 1 to end, column 2 to end

array([[23, 21],
       [23, 10],
       [18, 14],
       [11, 36]])

In [22]:
array_1[1:, 2:] = 0
print(array_1)

[[15 46 28 27]
 [10 20  0  0]
 [23 35  0  0]
 [39 39  0  0]
 [44 45  0  0]]


In [23]:
mask = array_1 > 25 # masking
print (mask)

[[False  True  True  True]
 [False False False False]
 [False  True False False]
 [ True  True False False]
 [ True  True False False]]


In [24]:
np.sum(mask) # return the sum of all the elements in the array
# true = 1 and false = 0

8

---

In [25]:
a = np.array([1,2,3,4,5])
print (a)

[1 2 3 4 5]


In [26]:
b = np.arange(6,11)
print (b)

[ 6  7  8  9 10]


In [27]:
a + b # matrix addition where final array is a[i] + b[i]
# arrays should have same shape

array([ 7,  9, 11, 13, 15])

In [28]:
b - a # matrix substraction where final array is b[i] - a[i]

array([5, 5, 5, 5, 5])

In [29]:
a * b # matrix multiplication where final array is a[i] * b[i]

array([ 6, 14, 24, 36, 50])

In [30]:
c = np.array([[1,2], [3,4]]) # multiplication takes place between the two corresponding cells
d = np.array([[1,2], [3,4]]) # like result[i,j] = a[i,j] * b[i,j]

In [31]:
c * d # result[i,j] = a[i,j] * b[i,j]

array([[ 1,  4],
       [ 9, 16]])

In [32]:
np.dot(c, d) # matrix multiplication

array([[ 7, 10],
       [15, 22]])

In [33]:
arr1 = np.random.randint(1, 5, (3,4))
arr2 = np.random.randint(1, 5, (4,5))
print (arr1)
print (arr2)
print(np.dot(arr1, arr2))

[[4 2 2 1]
 [1 1 4 2]
 [3 2 2 1]]
[[4 4 2 1 3]
 [1 4 4 3 1]
 [2 2 1 4 2]
 [3 1 3 4 4]]
[[25 29 21 22 22]
 [19 18 16 28 20]
 [21 25 19 21 19]]


---

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
array_2 = arr.reshape(2,5)
print (array_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [36]:
np.sqrt(array_2)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [37]:
np.max(array_2)

10

In [38]:
np.mean(array_2) # sum of all elements / the number of elements 

5.5

In [39]:
np.std(array_2) # standard deviation

2.8722813232690143

In [40]:
arr1

array([[4, 2, 2, 1],
       [1, 1, 4, 2],
       [3, 2, 2, 1]])

In [41]:
print (np.sum(arr1, axis = 0)) # sum across the columns
print (np.sum(arr1, axis = 1)) # sum across the rows

[8 5 8 4]
[9 8 8]


In [42]:
print (np.mean(arr1, axis = 1)) # mean across the row

[2.25 2.   2.  ]


---

In [43]:
arr2

array([[4, 4, 2, 1, 3],
       [1, 4, 4, 3, 1],
       [2, 2, 1, 4, 2],
       [3, 1, 3, 4, 4]])

In [44]:
arr2.flatten()

array([4, 4, 2, 1, 3, 1, 4, 4, 3, 1, 2, 2, 1, 4, 2, 3, 1, 3, 4, 4])

In [45]:
arr2.reshape(10,2) # total number of elements should be exactly the same in both the arrays

array([[4, 4],
       [2, 1],
       [3, 1],
       [4, 4],
       [3, 1],
       [2, 2],
       [1, 4],
       [2, 3],
       [1, 3],
       [4, 4]])

In [46]:
print (arr2.T) # returns the transpose of a matrix
print (np.transpose(arr2)) # both are same

[[4 1 2 3]
 [4 4 2 1]
 [2 4 1 3]
 [1 3 4 4]
 [3 1 2 4]]
[[4 1 2 3]
 [4 4 2 1]
 [2 4 1 3]
 [1 3 4 4]
 [3 1 2 4]]


In [47]:
a = np.array([[1,2], [3,4]])
print (a)

[[1 2]
 [3 4]]


In [48]:
b = np.array([[5,6], [7,8]])
print (b)

[[5 6]
 [7 8]]


In [49]:
c = np.array([[9,10], [11,12]])
print (c)

[[ 9 10]
 [11 12]]


In [50]:
np.vstack((a,b,c)) # stacks all the arrays vertically

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [51]:
np.hstack((a,b,c)) # stacks all the arrays horizontally

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

---

In [52]:
# broadcasting - helps to perform operations between arrays of different shapes
a = np.random.randint(1, 10, (3,3))
b = np.random.randint(1, 10, (1,3)) # atleast the row or column size has to be the same
print (a)
print (b)

[[2 9 5]
 [4 3 7]
 [2 5 7]]
[[1 5 4]]


In [53]:
a + b
# working:
# the smaller array repeats itself over to match the shape of the bigger array
# here, b becomes
# b = [[5,4,1]
#      [5,4,1]
#      [5,4,1]] 

array([[ 3, 14,  9],
       [ 5,  8, 11],
       [ 3, 10, 11]])